# TypeORM Connection configuration sample

# Tenant Common
default:
  name: 'default'
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  database: ''
  synchronize: false
  logging: true
  entities: ['dist/**/*.entity.js']
  entitiesDir: ['src/database/entities/common/**/*.entity.ts']
  migrations: ['dist/database/migrations/common/**/*.js']
  migrationsDir: ['src/database/migrations/common']
  subscribers: ['dist/database/subscribers/common/**/*.ts']
  subscribtersDir: ['src/database/subscribers/common/**/*.ts']

# Tennant
tenant: 
  name: 'tenant'
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  database: ''
  synchronize: false
  logging: true
  entities: ['dist/**/*.entity.js']
  entitiesDir: ['src/database/entities/tenant/**/*.entity.ts']
  migrations: ['dist/database/migrations/tenant/**/*.js']
  migrationsDir: ['src/database/migrations/tenant']
  subscribers: ['dist/database/subscribers/tenant/**/*.ts']
  subscribtersDir: ['src/database/subscribers/tenant/**/*.ts']
