# TypeORM Connection configuration sample

# Tenant Common
default:
  name: 'default'
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  database: ''
  synchronize: false
  logging: true
  entities: ['dist/database/entities/common/**/*.entity.js']
  entitiesDir: ['src/database/entities/common/**/*.entity.ts']
  migrations: ['dist/database/migrations/common/**/*.js']
  subscribers: ['dist/database/subscribers/common/**/*.ts']
  subscribtersDir: ['src/database/subscribers/common/**/*.ts']
  seeds: ['dist/database/seeds/common/**/*.seed.js']
  cli: 
    migrationsDir: 'src/database/migrations/common'

# Tennant
tenant: 
  name: 'tenant'
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: ''
  password: ''
  database: ''
  synchronize: false
  logging: true
  entities: ['dist/database/entities/tenant/**/*.entity.js']
  entitiesDir: ['src/database/entities/tenant/**/*.entity.ts']
  migrations: ['dist/database/migrations/tenant/**/*.js']
  subscribers: ['dist/database/subscribers/tenant/**/*.ts']
  subscribtersDir: ['src/database/subscribers/tenant/**/*.ts']
  seeds: ['dist/database/seeds/tenant/**/*.seed.js']
  cli: 
    migrationsDir: 'src/database/migrations/tenant'
